spring:
  application:
    name: service-order
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:service-order.yaml?group=DEFAULT_GROUP
server:
  port: 8000


logging:
  level:
    com.example.order.feign: debug

feign:
  sentinel:
    enabled: true
