spring:
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
      server-addr: 127.0.0.1:8848

    config:
      server-addr: 127.0.0.1:8848
  config:
    import-check:
      enabled: false
server:
  port: 9000

# 禁用检查

